version: '2'

services:

  postgres:
    image: postgres:11
    container_name: drfintegrations-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
