name: Release

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Build and publish
      uses: JRubics/poetry-publish@v1.16
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
